<?php
	include('getGuests.inc.php');
	include('getGuest.inc.php');
	include('getTables.inc.php');
	include('getTable.inc.php');
	include('getMeals.inc.php');
	include('getRelationship.inc.php');
	include('getChildren.inc.php');
?>
